language: cpp
dist: trusty
sudo: required

env:
  # (qttools5-dev-tools is explicitly included because of Debian bug #835295)
  - FLAGS="-DWITH_QT5=ON -DWITH_ALSA=ON -DWITH_GSM=ON -DWITH_SPEEX=ON -DWITH_ZRTP=ON" PACKAGES="libasound2-dev libgsm1-dev libspeex-dev libspeexdsp-dev libzrtpcpp-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools"

install:
  - sudo apt-get update
  - sudo apt-get -y install bison cmake flex libccrtp-dev libmagic-dev libreadline-dev libsndfile1-dev libucommon-dev libxml2-dev linux-libc-dev $PACKAGES

script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install $FLAGS ..
  - cmake --build . --target install
